version: "3.8"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: app
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - PG_URL=${PG_URL}
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./main"]
    networks:
      - app-network
    restart: on-failure

volumes:
  pg-data:

networks:
  app-network: